#!/bin/sh

set -e

for file in repomanage modules mock dcop bluez-utils; do
	dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/$file \
		1:1.3-1ubuntu6 -- "$@"
done

case "$1" in
    purge)
	rm -f /etc/bash_completion
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
