#!/bin/sh

set -e

for file in repomanage modules mock dcop bluez-utils; do
	dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/$file \
		1:1.3-1ubuntu6 -- "$@"
done

case "$1" in
    install|upgrade)
	if [ -e /usr/share/doc/bash/completion-contrib ]; then
	    rm -rf /usr/share/doc/bash/completion-contrib
	fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0


